services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: mysql:5.7  # Puedes usar mariadb:latest si prefieres MariaDB
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: nosecaensl       # Nombre de tu base de datos
      MYSQL_ROOT_PASSWORD: secret        # Contraseña para el usuario root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"  # phpMyAdmin estará disponible en http://localhost:8080
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: